# Generated by Django 5.0.7 on 2024-07-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('course_trainer', models.CharField(max_length=100)),
                ('course_objective', models.CharField(max_length=255)),
                ('course_duration', models.DurationField()),
                ('course_description', models.TextField()),
                ('pass_mark', models.IntegerField()),
                ('course_title', models.CharField(max_length=100)),
                ('course_teacher', models.CharField(max_length=100)),
                ('course_resources', models.CharField(max_length=255)),
                ('teaching_assistant', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
    ]
