# Generated by Django 5.0.7 on 2024-07-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('class_name', models.CharField(max_length=100)),
                ('class_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('room_allocation', models.CharField(max_length=100)),
                ('no_of_tables', models.PositiveSmallIntegerField()),
                ('no_of_students', models.PositiveSmallIntegerField()),
                ('class_representative', models.CharField(max_length=100)),
                ('class_goals', models.TextField()),
                ('class_meeting', models.CharField(max_length=100)),
                ('period_entity', models.CharField(max_length=100)),
            ],
        ),
    ]
