# Generated by Django 5.0.7 on 2024-07-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classeroom',
            field=models.ManyToManyField(related_name='students', to='classroom.classroom'),
        ),
    ]
